spring:
  application:
    name: observability

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - info
          - prometheus
          - prometheus-all

  endpoint:
    health:
      show-details: always
      probes:
        add-additional-paths: true
        enabled: true
  info:
    git:
      mode: simple
  logging:
    export:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    io.micrometer: DEBUG
---
spring:
  config:
    activate:
      on-profile: high-cardinality

metrics:
  allow-high-cardinality: true
---
spring:
  config:
    activate:
      on-profile: test-data

metrics:
  high-cardinality-tag-filters:
    - tag-name: high.key.one
      max-values: 60
    - tag-name: high.key.two
      max-values: 75
  high-cardinality-metrics:
    - test.application